# Generated by Django 3.1 on 2024-07-11 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_category', '0001_initial'),
        ('app_brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='photos/app_product')),
                ('stock', models.IntegerField()),
                ('import_from', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('manufacture', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('offers', models.BooleanField(default=False)),
                ('warrenty', models.IntegerField()),
                ('offer_precentage', models.IntegerField()),
                ('delivery_time', models.CharField(blank=True, max_length=200)),
                ('img1', models.ImageField(blank=True, upload_to='photos/app_product')),
                ('img2', models.ImageField(blank=True, upload_to='photos/app_product')),
                ('img3', models.ImageField(blank=True, upload_to='photos/app_product')),
                ('img4', models.ImageField(blank=True, upload_to='photos/app_product')),
                ('desc', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_brand.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_category.category')),
            ],
        ),
    ]
