# Generated by Django 3.1 on 2024-07-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_precentage',
            field=models.IntegerField(blank=True),
        ),
    ]
