# Generated by Django 3.1 on 2024-07-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_auto_20240711_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_precentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warrenty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
