# Generated by Django 3.1 on 2024-07-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('quantity', 'quantity')], max_length=255),
        ),
    ]
