# Generated by Django 3.1 on 2024-07-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
