# Generated by Django 4.0.3 on 2024-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0009_review_review_review_status_review_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='message',
        ),
        migrations.AlterField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
